config/routes.rb
Rails.application.routes.draw do  
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  resources :requests, except: :show
  devise_for :users
  resources :categories
  resources :books
  resources :users
  namespace :admin do
  	root 'requests#index'
    resources :requests, only: [:index, :update]
    patch 'update_request' => 'requests#update'
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  
  validates :target_id, :action_type, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  has_many :reviews
  has_many :likes
  has_many :comments
  has_many :favorites
  has_many :book_states
  
  validates :title, presence: true, length: {minimum: 6}
  validates :author, presence: true, length: {minimum: 6}
  validates :publish_date, :number_page, :rating, presence: true
  validate :image_size

  mount_uploader :image, ImageUploader
  
  private

  def image_size
    errors.add(:image, "should be less than 5MB") if image.size > 5.megabytes
  end
end

app/models/book_state.rb
class BookState < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  
  validates :state, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
  
  mount_uploader :image, ImageUploader
  
  validates :name, presence: true
  validate :image_size

  private
  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "Should be less than 5MB")
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
  belongs_to :book
  
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  validates :followed_id, :follower_id, presence: true
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  
  validates :book_name, :book_url, presence: true

  def is_accepted?
  	self.state == "accepted"
  end

  def is_rejected?
  	self.state == "rejected"
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
  has_many :comments
  
  validates :content, :rate, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  has_many :comments
  has_many :likes
  has_many :reviews
  has_many :book_states
  has_many :favorites
  has_many :relationships
  has_many :activities
  has_many :requests

  def is_admin?
    self.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:email, :username)}
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, 
      :username, :image, :password, :password_confirmation)}
  end

  def admin_user
    redirect_to root_url  unless current_user.is_admin?  
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :get_categories, only: [:new, :edit]

  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new book_params
    if @book.save
      respond_to do |format|
        format.html {redirect_to root_url, notice: "Book is created"}
        format.js
      end
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    if @book.update_attributes book_params
      flash[:success] = "updated book!"
      redirect_to @book
    else
      flash.now[:danger] = "Not success!"
      render "edit"
    end
  end

  def index
  end

  def show
  end

  private

  def book_params
    params.require(:book).permit :title, :author, :publish_date, :number_page,
      :image, :category_id
  end

  def get_categories
    @categories = Category.order(:name).map{|category| [category.name, category.id]}
  end  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @categories = Category.paginate page: params[:page]
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Created success"
      redirect_to categories_url
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      flash[:success] = "Category updated"
      redirect_to categories_url
    else
      render 'edit'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category Deleted"
    redirect_to categories_url
  end

  private
  def category_params
    params.require(:category).permit :name, :image
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @requests = current_user.requests.order created_at: :desc
    @requests = @requests.paginate page: params[:page], per_page: 15
  end

  def new
    @request = current_user.requests.build
  end

  def create
    @request = current_user.requests.build request_params
    if @request.save
      flash[:success] = "Request is created!"
      redirect_to requests_url    
    end
  end  

  def destroy
    @request.destroy
    flash[:success] = "Request is deleted!"
    redirect_to requests_url
  end

  private
  def request_params
    params.require(:request).permit :book_name, :book_url, :state
  end   
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.paginate page: params[:page]
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='')
    base_title = "Ruby on rails"
    if page_title.empty?
      base_title
    else
      "#{page_title}|#{base_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>
    The <%= link_to 'Book Review System', root_path %>
    by <%= link_to 'Team 2 of Intermship group', '#' %>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
      <li><a href='#'>News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='container'>
    <%= link_to 'Book Review System', root_path, id: 'logo' %>
    <nav>
      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Category', categories_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% unless user_signed_in? %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% else %>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete
            %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src='//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js'>
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' =>
    true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class='container'>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>